DROP DATABASE IF EXISTS sdc;
CREATE DATABASE sdc;
USE sdc;

CREATE TABLE hotels (
  id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar(150) NOT NULL,
  city varchar(250) NOT NULL
);

CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY,
  username
  avatar
  citycontributions
  helpful
);

CREATE TABLE (

);

CREATE TABLE (

);